efault: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: notebook_development

test:
  <<: *default
  database: notebook_test

production:
  <<: *default
  database: notebook_production
  username: 
  password: 